/* (C)2026 Christian Schnapka / Macstab GmbH */
package com.macstab.chaos.connection.annotation.l1.connect;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import com.macstab.chaos.connection.annotation.l1.ConnectionErrnoBinding;
import com.macstab.chaos.connection.model.Errno;
import com.macstab.chaos.connection.model.NetOperation;
import com.macstab.chaos.core.extension.ChaosL1;
import com.macstab.chaos.core.extension.OnMissingEnv;

/**
 * Injects {@code ECONNRESET} into {@code connect(2)}, causing the call to return {@code -1} with
 * {@code errno = ECONNRESET} as if the remote host sent a TCP RST segment during the connection
 * handshake after the SYN-ACK was received.
 *
 * <h2>What this annotation is</h2>
 *
 * <p>L1 libchaos primitive. Encodes exactly one (operation = {@code CONNECT}, errno = {@code
 * ECONNRESET}) tuple. A Bernoulli trial with probability {@link #toxicity} is run on each
 * intercepted {@code connect} call; when it fires the interposer returns {@code -1} with {@code
 * errno = ECONNRESET} without performing any real kernel operation. No runtime operation-errno
 * validation is needed.
 *
 * <h2>What chaos this applies</h2>
 *
 * <ol>
 *   <li>{@code @SyscallLevelChaos(LibchaosLib.NET)} on the container definition causes the
 *       extension to upload {@code libchaos-net.so} into the container and prepend it to {@code
 *       LD_PRELOAD} before the process starts.
 *   <li>The shared library interposes {@code connect}, {@code accept}, {@code socket}, {@code
 *       bind}, {@code listen}, {@code shutdown}, {@code send}, {@code recv}, and {@code poll} at
 *       the dynamic-linker level.
 *   <li>On each intercepted {@code connect} call a Bernoulli trial with probability {@link
 *       #toxicity} is conducted; when it fires the interposer returns {@code -1} and sets {@code
 *       errno = ECONNRESET}.
 * </ol>
 *
 * <h2>Observable effects and what to assert in tests</h2>
 *
 * <ul>
 *   <li>The connection attempt fails immediately after the server sends a RST; no connection fd is
 *       created and the connecting socket must be closed and a new one created before retrying.
 *   <li>Connection pools that reuse the socket after a connect-time reset will encounter errors on
 *       the first send; assert that pools detect connect failures and do not return the socket to
 *       the pool for reuse.
 *   <li>Assert that the application distinguishes {@code ECONNRESET} from {@code ECONNREFUSED}: a
 *       reset during handshake indicates a mid-flight network event (e.g., load balancer failover
 *       or firewall rule change), not a permanently closed port; retry logic should differ
 *       accordingly.
 *   <li>Assert that observability tooling records the reset as a connection failure event with
 *       enough context (remote address, port, timestamp) to correlate with load-balancer health
 *       events.
 * </ul>
 *
 * <p>In production, {@code ECONNRESET} during {@code connect} occurs when a load balancer or
 * firewall terminates in-flight SYN packets with RST during a failover event, when a stateful
 * firewall loses its connection tracking table and sends RST to packets it no longer recognises,
 * and when a server process receives a SYN but sends RST because its accept queue is full and the
 * {@code tcp_abort_on_overflow} sysctl is enabled.
 *
 * <h2>Deep technical dive</h2>
 *
 * <p>In normal TCP, a connection reset during the handshake phase is unusual. The kernel returns
 * {@code ECONNRESET} from a blocking {@code connect} when it receives a RST segment while waiting
 * for the SYN-ACK. This can happen if the server's accept queue overflows and the server is
 * configured with {@code tcp_abort_on_overflow = 1} (the default is 0, which causes the kernel to
 * silently drop the SYN instead). In containerised environments, load balancers that perform TCP
 * health checks can also send RST segments to connections they decide to terminate mid-handshake
 * during their own reconfiguration.
 *
 * <p>The distinction from {@code ECONNREFUSED} matters for connection pool retry logic: {@code
 * ECONNREFUSED} is generated by the remote kernel instantly (RST in response to SYN), while {@code
 * ECONNRESET} during connect typically arrives after at least one round-trip (RST in response to
 * ACK or data). Application code that counts both as "connection failure" and applies a single
 * retry strategy may retry too aggressively on refusals (triggering thundering-herd) or too
 * conservatively on resets (missing brief recovery windows).
 *
 * <p>Java maps {@code ECONNRESET} from {@code connect} to a {@code SocketException} with the
 * message "Connection reset". Note that the same message is used for resets on established
 * connections (from {@code recv} or {@code send}); application code that tries to distinguish
 * connect-time resets from established-connection resets by examining the exception message will
 * fail. The only reliable way to distinguish them is by tracking the connection lifecycle state at
 * the connection-pool level.
 *
 * <h2>Example</h2>
 *
 * <pre>{@code
 * @RedisStandalone
 * @SyscallLevelChaos(LibchaosLib.NET)
 * @ChaosConnectEconnreset(toxicity = 0.05)
 * class ConnectEconnresetTest {
 *   @Test
 *   void connectionPoolRecreatesSocketAfterConnectTimeReset(ConnectionInfo info) {
 *     // assert that pool creates a new socket on connect reset rather than reusing the failed one
 *   }
 * }
 * }</pre>
 *
 * @author Christian Schnapka - Macstab GmbH
 * @see ChaosConnectEconnrefused
 * @see ChaosConnectEtimedout
 * @see com.macstab.chaos.connection.annotation.l1.ConnectionErrnoBinding
 */
@Repeatable(ChaosConnectEconnreset.Repeatable.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
@ChaosL1(
    translator = "com.macstab.chaos.connection.annotation.l1.translators.ConnectionErrnoTranslator")
@ConnectionErrnoBinding(operation = NetOperation.CONNECT, errno = Errno.ECONNRESET)
public @interface ChaosConnectEconnreset {

  /**
   * @return probability the errno fires when matched, in {@code (0.0, 1.0]}
   */
  double toxicity() default 1.0;

  /**
   * @return container id to bind to ({@code ""} = every matching container)
   */
  String id() default "";

  /**
   * @return policy when the active backend cannot honour libchaos-net
   */
  OnMissingEnv onMissingEnv() default OnMissingEnv.ERROR;

  /**
   * Container that enables repeating this annotation on the same element. Do not use directly —
   * Java adds it automatically when the annotation appears more than once on the same target.
   *
   * <p>Example:
   *
   * <pre>{@code
   * @ChaosConnectEconnreset(id = "primary",  probability = 0.001)
   * @ChaosConnectEconnreset(id = "replica",  probability = 0.01)
   * class MultiContainerTest { ... }
   * }</pre>
   */
  @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.RUNTIME)
  @java.lang.annotation.Target({
    java.lang.annotation.ElementType.TYPE,
    java.lang.annotation.ElementType.METHOD,
    java.lang.annotation.ElementType.FIELD
  })
  @interface Repeatable {
    ChaosConnectEconnreset[] value();
  }
}
