/* (C)2026 Christian Schnapka / Macstab GmbH */
package com.macstab.chaos.connection.annotation.l1.send;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import com.macstab.chaos.connection.annotation.l1.ConnectionErrnoBinding;
import com.macstab.chaos.connection.model.Errno;
import com.macstab.chaos.connection.model.NetOperation;
import com.macstab.chaos.core.extension.ChaosL1;
import com.macstab.chaos.core.extension.OnMissingEnv;

/**
 * Injects {@code ENOMEM} into {@code send(2)}, causing the call to return {@code -1} with {@code
 * errno = ENOMEM} as if the kernel's memory allocator failed to allocate the internal socket buffer
 * structures needed to queue the outgoing data for transmission.
 *
 * <h2>What this annotation is</h2>
 *
 * <p>L1 libchaos primitive. Encodes exactly one (operation = {@code SEND}, errno = {@code ENOMEM})
 * tuple. A Bernoulli trial with probability {@link #toxicity} is run on each intercepted {@code
 * send} call; when it fires the interposer returns {@code -1} with {@code errno = ENOMEM} without
 * performing any real kernel operation. No runtime operation-errno validation is needed.
 *
 * <h2>What chaos this applies</h2>
 *
 * <ol>
 *   <li>{@code @SyscallLevelChaos(LibchaosLib.NET)} on the container definition causes the
 *       extension to upload {@code libchaos-net.so} into the container and prepend it to {@code
 *       LD_PRELOAD} before the process starts.
 *   <li>The shared library interposes {@code connect}, {@code accept}, {@code socket}, {@code
 *       bind}, {@code listen}, {@code shutdown}, {@code send}, {@code recv}, and {@code poll} at
 *       the dynamic-linker level.
 *   <li>On each intercepted {@code send} call a Bernoulli trial with probability {@link #toxicity}
 *       is conducted; when it fires the interposer returns {@code -1} and sets {@code errno =
 *       ENOMEM}.
 * </ol>
 *
 * <h2>Observable effects and what to assert in tests</h2>
 *
 * <ul>
 *   <li>{@code ENOMEM} from {@code send} indicates global kernel memory exhaustion rather than a
 *       per-socket buffer condition; unlike {@code ENOBUFS} (buffer pool exhausted) or {@code
 *       EAGAIN} (send buffer full), {@code ENOMEM} signals that the kernel's slab allocator could
 *       not satisfy an allocation request at the socket layer.
 *   <li>The connection is not necessarily broken by {@code ENOMEM}: the socket remains valid and a
 *       subsequent {@code send} may succeed if kernel memory pressure is relieved. Assert that the
 *       application does not close the socket on receipt of {@code ENOMEM}.
 *   <li>Assert that the application backs off and retries with exponential delay rather than
 *       spinning in a tight retry loop, which would worsen kernel memory pressure.
 *   <li>Assert that the application emits a kernel memory pressure event or metric, enabling
 *       operators to correlate the failure with container memory limit settings and cgroup usage.
 * </ul>
 *
 * <p>In production, {@code ENOMEM} from {@code send} occurs during severe kernel memory pressure,
 * typically when the container's cgroup memory limit is nearly exhausted and kernel slab caches
 * cannot grow to satisfy new network buffer allocations. It is distinct from user-space {@code
 * OutOfMemoryError}: the JVM heap may be healthy while the kernel's memory is exhausted.
 *
 * <h2>Deep technical dive</h2>
 *
 * <p>The kernel's network stack calls {@code sock_wmalloc()} or {@code sk_stream_alloc_skb()} to
 * allocate an {@code sk_buff} structure to hold the outgoing data. These allocators call {@code
 * kmalloc()} or {@code alloc_skb()} internally; when the slab allocator returns NULL (due to memory
 * pressure), the network stack propagates {@code ENOMEM} up to the {@code send} syscall. Unlike
 * {@code ENOBUFS}, which is returned by the socket layer's per-protocol buffer accounting, {@code
 * ENOMEM} is returned by the general-purpose kernel memory allocator.
 *
 * <p>The distinction between {@code ENOMEM} and {@code ENOBUFS} is subtle but important: both
 * indicate kernel memory pressure, but {@code ENOBUFS} is returned by the socket's own buffer quota
 * system (tracked per socket via {@code sk_wmem_alloc}), while {@code ENOMEM} is returned when the
 * underlying slab allocator fails regardless of per-socket quotas. In practice, {@code ENOBUFS} is
 * more common on send paths; {@code ENOMEM} appears only under severe system-wide memory pressure.
 *
 * <p>Java maps {@code ENOMEM} from {@code send} to a {@code SocketException} with the message
 * "Cannot allocate memory". This message is generated by {@code strerror(ENOMEM)} in glibc;
 * application code that inspects the exception message to identify the error should be aware that
 * the message text varies across operating systems and glibc versions. The JVM heap remains
 * unaffected — the error originates in kernel space and does not trigger a JVM {@code
 * OutOfMemoryError}.
 *
 * <p>Containers running under strict cgroup memory limits are particularly susceptible to this
 * condition during traffic spikes: when the JVM's GC pressure causes the operating system to
 * reclaim page cache, kernel slab allocations for network buffers may start failing. Tuning {@code
 * vm.min_free_kbytes} and the container memory limit to leave headroom for kernel slab caches is
 * the standard mitigation.
 *
 * <h2>Example</h2>
 *
 * <pre>{@code
 * @RedisStandalone
 * @SyscallLevelChaos(LibchaosLib.NET)
 * @ChaosSendEnomem(toxicity = 0.001)
 * class SendEnomemTest {
 *   @Test
 *   void applicationBacksOffOnKernelMemoryExhaustion(ConnectionInfo info) {
 *     // assert that the sender retries with delay and does not spin on ENOMEM
 *   }
 * }
 * }</pre>
 *
 * @author Christian Schnapka - Macstab GmbH
 * @see ChaosSendEnobufs
 * @see ChaosSendEagain
 * @see com.macstab.chaos.connection.annotation.l1.ConnectionErrnoBinding
 */
@Repeatable(ChaosSendEnomem.Repeatable.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
@ChaosL1(
    translator = "com.macstab.chaos.connection.annotation.l1.translators.ConnectionErrnoTranslator")
@ConnectionErrnoBinding(operation = NetOperation.SEND, errno = Errno.ENOMEM)
public @interface ChaosSendEnomem {

  /**
   * @return probability the errno fires when matched, in {@code (0.0, 1.0]}
   */
  double toxicity() default 1.0;

  /**
   * @return container id to bind to ({@code ""} = every matching container)
   */
  String id() default "";

  /**
   * @return policy when the active backend cannot honour libchaos-net
   */
  OnMissingEnv onMissingEnv() default OnMissingEnv.ERROR;

  /**
   * Container that enables repeating this annotation on the same element. Do not use directly —
   * Java adds it automatically when the annotation appears more than once on the same target.
   *
   * <p>Example:
   *
   * <pre>{@code
   * @ChaosSendEnomem(id = "primary",  probability = 0.001)
   * @ChaosSendEnomem(id = "replica",  probability = 0.01)
   * class MultiContainerTest { ... }
   * }</pre>
   */
  @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.RUNTIME)
  @java.lang.annotation.Target({
    java.lang.annotation.ElementType.TYPE,
    java.lang.annotation.ElementType.METHOD,
    java.lang.annotation.ElementType.FIELD
  })
  @interface Repeatable {
    ChaosSendEnomem[] value();
  }
}
