/* (C)2026 Christian Schnapka / Macstab GmbH */
package com.macstab.chaos.toxiproxy.network;

import java.io.IOException;

import lombok.NonNull;

import com.macstab.chaos.toxiproxy.context.ContainerContext;

/**
 * Contract for transparent TCP port redirection via Linux iptables inside a container, enabling
 * Toxiproxy to intercept traffic without requiring client-side configuration changes.
 *
 * <h2>Why This Exists: The Transparency Problem</h2>
 *
 * <p>Toxiproxy listens on a <em>proxy port</em> (e.g., 16379) and forwards to the real service on
 * the original <em>service port</em> (e.g., 6379). Without transparent redirection, clients
 * would need to connect to the proxy port explicitly — changing the application's connection
 * string, which defeats the purpose of chaos testing (you want to test the real application code,
 * not a test-specific variant). With iptables NAT redirection, clients connect to the original
 * service port and the Linux kernel silently rewrites the destination port before the packet
 * reaches the application layer.
 *
 * <h2>iptables NAT Mechanism</h2>
 *
 * <p>The redirect is implemented as two iptables rules in the NAT table:
 * <pre>
 * iptables -t nat -A PREROUTING -p tcp --dport {servicePort} -j REDIRECT --to-port {proxyPort}
 * iptables -t nat -A OUTPUT     -p tcp --dport {servicePort} -j REDIRECT --to-port {proxyPort}
 * </pre>
 *
 * <p><strong>Why both PREROUTING and OUTPUT:</strong>
 * <ul>
 *   <li><strong>PREROUTING</strong> applies to packets entering the container from an external
 *       network interface (e.g., the test JVM connecting to the container via Docker's bridge
 *       network). Without PREROUTING, external clients bypass Toxiproxy.
 *   <li><strong>OUTPUT</strong> applies to packets originating from processes <em>within</em>
 *       the container that connect to {@code localhost:{servicePort}}. Without OUTPUT, in-container
 *       traffic (e.g., an application process within the same container connecting to its own
 *       service) bypasses Toxiproxy. Note: the test JVM connects from outside the container and
 *       is handled by PREROUTING; OUTPUT is required for intra-container connectivity scenarios.
 * </ul>
 *
 * <p>The actual command strings are generated by
 * {@link com.macstab.chaos.core.command.network.NetworkCommandBuilder}, which is obtained from
 * {@link com.macstab.chaos.toxiproxy.context.ContainerContext#platform()}. This abstraction
 * allows platform-specific implementations (standard iptables vs. BusyBox iptables) to provide
 * different command syntax without modifying this layer.
 *
 * <h2>Prerequisite: NET_ADMIN Capability</h2>
 *
 * <p>iptables requires {@code CAP_NET_ADMIN}. Containers without this capability will receive
 * "Operation not permitted" from the kernel. The capability must be granted at container creation
 * time:
 * <pre>{@code
 * container.withCreateContainerCmdModifier(cmd ->
 *     cmd.getHostConfig().withCapAdd(Capability.NET_ADMIN));
 * }</pre>
 * There is no runtime fallback. Missing NET_ADMIN will cause {@link #setupRedirect} to throw
 * {@link IOException} with a non-zero exit code from the iptables command.
 *
 * <h2>Cleanup Semantics and the Nuclear Reset Problem</h2>
 *
 * <p>{@link #clearAllRedirects(ContainerContext)} flushes the entire NAT table ({@code iptables
 * -t nat -F}), removing ALL redirect rules — not just ones installed by this module. This is
 * intentional for full container teardown but destroys rules installed by other modules or
 * processes. For surgical cleanup of a single proxy's rules, use
 * {@link #removeRedirect(ContainerContext, int, int)}. Callers must choose between:
 * <ul>
 *   <li>{@link #removeRedirect} — remove one port pair's rules; leaves other rules intact
 *       (use for per-proxy cleanup)
 *   <li>{@link #clearAllRedirects} — flush all nat rules; use only in full teardown
 * </ul>
 *
 * <h2>Relationship to {@link com.macstab.chaos.toxiproxy.api.ToxiproxyApiClient}</h2>
 *
 * <p>iptables rules and Toxiproxy proxy entries are orthogonal. A Toxiproxy proxy entry without
 * iptables rules means traffic reaches Toxiproxy only if clients explicitly connect to the proxy
 * port. iptables rules without a Toxiproxy proxy entry cause connections to the proxy port to
 * be refused (nothing listening). Both must be created together ({@link #setupRedirect} +
 * {@link com.macstab.chaos.toxiproxy.api.ToxiproxyApiClient#createProxy}) and destroyed together
 * ({@link #removeRedirect} +
 * {@link com.macstab.chaos.toxiproxy.api.ToxiproxyApiClient#deleteProxy}) to maintain
 * system consistency.
 *
 * <h2>Thread Safety</h2>
 *
 * <p>Implementations must be stateless. iptables is not concurrency-safe at the kernel level —
 * concurrent modifications to the same NAT table from multiple threads may produce races on the
 * rule counter and ordering. In practice this is not a concern in test scenarios where each test
 * manages its own proxies sequentially.
 *
 * @author Christian Schnapka - Macstab GmbH
 * @see NetworkRedirectManager for the production implementation
 * @see com.macstab.chaos.toxiproxy.api.ToxiproxyApiClient for Toxiproxy proxy management
 */
public interface NetworkRedirect {

  /**
   * Installs iptables NAT rules to transparently redirect TCP traffic from {@code servicePort}
   * to {@code proxyPort}, enabling Toxiproxy to intercept connections without client changes.
   *
   * <p><strong>What this does precisely:</strong> Adds one PREROUTING and one OUTPUT rule in
   * the iptables NAT table. After this call, any TCP packet destined for {@code servicePort}
   * inside the container — regardless of whether it originates externally (PREROUTING) or
   * internally (OUTPUT) — is silently redirected to {@code proxyPort} by the Linux kernel
   * <em>before</em> it reaches the userspace socket layer. The application and the client
   * observe no difference in address; only the kernel and Toxiproxy are aware of the redirect.
   *
   * <p><strong>Not idempotent:</strong> Calling this method twice with the same port pair appends
   * duplicate rules to the iptables chain. Duplicate rules have no additional effect on traffic
   * but accumulate and must each be removed individually. Higher-level orchestration should
   * check rule existence before calling, or use a higher-level idempotency mechanism.
   *
   * <p><strong>Failure behavior:</strong> If the container lacks NET_ADMIN capability, the
   * iptables command exits non-zero and this method throws {@link IOException}. The Toxiproxy
   * proxy entry (if already created) remains but traffic will not reach it — callers must handle
   * this inconsistency (clean up the proxy entry) to avoid orphaned state.
   *
   * @param ctx resolved container context; the container must have NET_ADMIN capability
   * @param servicePort the port clients connect to (the "real" service port); [1, 65535]
   * @param proxyPort the Toxiproxy listen port where traffic is redirected; [1, 65535]
   * @throws IOException if the iptables command fails (most commonly: missing NET_ADMIN
   *                     capability, iptables binary not installed, container not running)
   * @throws IllegalArgumentException if either port is outside [1, 65535]
   * @throws NullPointerException if ctx is null
   */
  void setupRedirect(
      @NonNull ContainerContext ctx, int servicePort, int proxyPort) throws IOException;

  /**
   * Removes the iptables NAT rules previously installed for the given port pair, restoring
   * direct traffic flow from {@code servicePort} to the real service.
   *
   * <p><strong>What this does precisely:</strong> Removes the PREROUTING and OUTPUT rules for
   * the specified port pair from the iptables NAT table. After this call, TCP connections to
   * {@code servicePort} are no longer redirected — they reach the real service directly,
   * bypassing Toxiproxy entirely.
   *
   * <p><strong>Coupling with proxy deletion:</strong> Removing the iptables rules while the
   * Toxiproxy proxy entry still exists leaves an orphaned proxy listening on {@code proxyPort}
   * that receives no traffic. This is benign but wastes resources and may cause confusion.
   * Always pair with {@link com.macstab.chaos.toxiproxy.api.ToxiproxyApiClient#deleteProxy}.
   *
   * <p><strong>Duplicate-rule behavior:</strong> If {@link #setupRedirect} was called multiple
   * times for the same port pair (creating duplicates), this method removes only <em>one</em>
   * occurrence. Subsequent duplicates remain and continue redirecting traffic. This is a known
   * limitation; use {@link #clearAllRedirects} to ensure a clean state.
   *
   * @param ctx resolved container context
   * @param servicePort the original service port; [1, 65535]
   * @param proxyPort the Toxiproxy port; [1, 65535]
   * @throws IOException if the iptables command fails
   * @throws IllegalArgumentException if either port is outside [1, 65535]
   * @throws NullPointerException if ctx is null
   */
  void removeRedirect(
      @NonNull ContainerContext ctx, int servicePort, int proxyPort) throws IOException;

  /**
   * Flushes all rules from the iptables NAT table inside the container, removing every port
   * redirect regardless of origin.
   *
   * <p><strong>NUCLEAR OPERATION — use only in full teardown:</strong> This method executes the
   * equivalent of {@code iptables -t nat -F}, which removes <em>all</em> rules from <em>all</em>
   * chains in the NAT table — not just rules installed by this module. Any rules installed by
   * other chaos modules (connection module, cache module), by the container image itself, or by
   * any other mechanism are also removed.
   *
   * <p><strong>When to use this:</strong> Only in {@code @AfterAll} during full container
   * teardown when the container itself will be discarded. The side effect of destroying other
   * modules' rules is acceptable in this context.
   *
   * <p><strong>When NOT to use this:</strong> Never in {@code @AfterEach} or per-proxy cleanup.
   * Use {@link #removeRedirect} for surgical per-proxy rule removal.
   *
   * <p><strong>Non-zero exit handling:</strong> If no rules exist (fresh container, or after a
   * previous flush), the iptables flush command still exits with code 0. Non-zero exit codes
   * from flush operations are unusual and typically indicate iptables binary issues or kernel
   * module not loaded. Implementations should log a warning rather than throw in this case,
   * since teardown should proceed regardless.
   *
   * @param ctx resolved container context
   * @throws IOException if the iptables command fails with an unexpected error (not "no rules
   *                     to flush")
   * @throws NullPointerException if ctx is null
   */
  void clearAllRedirects(@NonNull ContainerContext ctx) throws IOException;
}
