/* (C)2026 Christian Schnapka / Macstab GmbH */
package com.macstab.chaos.toxiproxy.network;

import java.io.IOException;

import com.macstab.chaos.toxiproxy.context.ContainerContext;

/**
 * Manages iptables port redirection inside a container to transparently route traffic through
 * Toxiproxy.
 *
 * <h2>Why Port Redirection Is Necessary</h2>
 *
 * <p>Toxiproxy listens on a <em>proxy port</em> (e.g., 16379) and forwards to the real service on a
 * <em>service port</em> (e.g., 6379). Without redirection, clients must explicitly connect to the
 * proxy port — changing the application under test and making chaos injection intrusive.
 *
 * <p>With iptables redirection, clients connect to the original service port (6379) and the kernel
 * silently reroutes the traffic to Toxiproxy (16379). The application code is unchanged; the proxy
 * is completely transparent.
 *
 * <h2>iptables Mechanism</h2>
 *
 * <p>Two iptables rules are installed per redirect — one for traffic entering from external clients
 * (PREROUTING) and one for traffic originated within the container itself (OUTPUT):
 *
 * <pre>
 * iptables -t nat -A PREROUTING -p tcp --dport {servicePort} -j REDIRECT --to-port {proxyPort}
 * iptables -t nat -A OUTPUT     -p tcp --dport {servicePort} -j REDIRECT --to-port {proxyPort}
 * </pre>
 *
 * <p>The actual commands are generated by {@link
 * com.macstab.chaos.core.command.network.NetworkCommandBuilder} and are platform-specific.
 *
 * <h2>Requirements</h2>
 *
 * <ul>
 *   <li>The container must have {@code NET_ADMIN} capability.
 *   <li>{@code iptables} must be installed (handled by {@link
 *       com.macstab.chaos.toxiproxy.lifecycle.ToxiproxyInstaller}).
 * </ul>
 *
 * <h2>Context Passing</h2>
 *
 * <p>All methods receive a pre-resolved {@link ContainerContext}. The {@link
 * com.macstab.chaos.core.command.network.NetworkCommandBuilder} is obtained from {@link
 * ContainerContext#platform()} — no platform detection inside implementations.
 *
 * <h2>Default Implementation</h2>
 *
 * <p>{@link NetworkRedirectManager} is the production implementation.
 *
 * @author Christian Schnapka - Macstab GmbH
 */
public interface NetworkRedirect {

  /**
   * Install iptables rules to redirect {@code servicePort} traffic to {@code proxyPort}.
   *
   * <p>Adds PREROUTING and OUTPUT nat rules so that any traffic directed at {@code servicePort}
   * inside the container is silently rerouted to {@code proxyPort} (where Toxiproxy listens).
   * Clients connecting to the original service port experience the proxy transparently.
   *
   * <p>Both ports must be in the range [1, 65535].
   *
   * @param ctx resolved container context (must have NET_ADMIN capability)
   * @param servicePort the original service port clients connect to (e.g., 6379 for Redis)
   * @param proxyPort the Toxiproxy listening port (e.g., 16379)
   * @throws IOException if the iptables command fails or the shell execution throws
   * @throws IllegalArgumentException if either port is outside [1, 65535]
   * @throws NullPointerException if ctx is null
   */
  void setupRedirect(ContainerContext ctx, int servicePort, int proxyPort) throws IOException;

  /**
   * Remove the iptables redirect rules for a specific port pair.
   *
   * <p>Removes the PREROUTING and OUTPUT nat rules previously added by {@link
   * #setupRedirect(ContainerContext, int, int)} for the given port pair. After removal, traffic to
   * {@code servicePort} is no longer redirected.
   *
   * @param ctx resolved container context
   * @param servicePort the original service port
   * @param proxyPort the proxy port
   * @throws IOException if the iptables command fails or the shell execution throws
   * @throws IllegalArgumentException if either port is outside [1, 65535]
   * @throws NullPointerException if ctx is null
   */
  void removeRedirect(ContainerContext ctx, int servicePort, int proxyPort) throws IOException;

  /**
   * Flush all iptables nat rules, removing every port redirect installed in this container.
   *
   * <p>Executes the platform-appropriate "clear all redirects" command (typically {@code iptables
   * -t nat -F}). Called during a full reset to restore the container to its original network state.
   *
   * <p>If no rules exist (e.g., called before any proxy was created), this method logs a warning
   * and returns without error — it does not throw.
   *
   * @param ctx resolved container context
   * @throws IOException if the iptables command fails with an unexpected error
   * @throws NullPointerException if ctx is null
   */
  void clearAllRedirects(ContainerContext ctx) throws IOException;
}
