/* (C)2026 Christian Schnapka / Macstab GmbH */
package com.macstab.chaos.toxiproxy.config;

import java.util.Objects;

import lombok.NonNull;

/**
 * Immutable value record fully specifying one Toxiproxy proxy's TCP interception configuration.
 *
 * <h2>What This Represents</h2>
 *
 * <p>A Toxiproxy proxy intercepts TCP connections to the real service port and forwards them
 * through Toxiproxy so that fault injection can be applied. This record captures all four
 * parameters required to set up that interception:
 *
 * <pre>
 * Test JVM / external client
 *   → hostname:servicePort  (what clients connect to)
 *       → iptables PREROUTING redirect (kernel-level, transparent)
 *           → localhost:proxyPort  (Toxiproxy, inside the container)
 *               → fault injection applied
 *                   → localhost:servicePort  (real service, inside the container)
 * </pre>
 *
 * <h2>Java Record (JEP 395)</h2>
 *
 * <p>This type is a Java record, providing:
 *
 * <ul>
 *   <li>A canonical constructor (all four components, in declaration order)
 *   <li>Accessor methods with record-style naming: {@code proxyName()}, {@code servicePort()},
 *       {@code proxyPort()}, {@code containerHostname()} — NOT {@code getXxx()}
 *   <li>Compiler-generated {@code equals()}, {@code hashCode()}, and {@code toString()}
 *   <li>Implicit {@code final} on all fields — instances are deeply immutable for primitives and
 *       String (String is immutable)
 * </ul>
 *
 * The compact constructor (no parameter list) intercepts the canonical constructor to validate
 * invariants before any field assignment.
 *
 * <h2>Critical: containerHostname Must Not Be "localhost"</h2>
 *
 * <p>The {@code containerHostname} field must be the address that the test JVM uses to connect to
 * the container — obtained via {@code container.getHost()}, not the literal string {@code
 * "localhost"}. This is a subtle but critical distinction:
 *
 * <ul>
 *   <li>On Linux with native Docker, {@code container.getHost()} returns the container's bridge IP
 *       (e.g., {@code 172.17.0.2}) or the Docker host IP.
 *   <li>On Docker Desktop (macOS/Windows), {@code container.getHost()} returns the Docker Desktop
 *       VM's address, accessible from the macOS/Windows host.
 *   <li>If a client connects to {@code localhost:servicePort}, the iptables PREROUTING rule does
 *       NOT apply (PREROUTING only intercepts externally-arriving packets). The client would bypass
 *       Toxiproxy entirely. The OUTPUT chain handles intra-container loopback traffic, but the test
 *       JVM is not inside the container.
 * </ul>
 *
 * <h2>Port Collision Not Validated</h2>
 *
 * <p>This record validates that both ports are in [1, 65535] but does NOT validate that {@code
 * servicePort != proxyPort}. Setting them equal would result in an iptables redirect loop (traffic
 * redirected to the same port it came from, causing the OS to immediately redirect it again —
 * infinite redirect loop until the connection is reset). Callers are responsible for ensuring the
 * two ports are distinct.
 *
 * <h2>Thread Safety</h2>
 *
 * <p>Unconditionally thread-safe. All four components are immutable ({@code int} primitives and
 * {@code String} which is immutable in Java). Instances may be freely shared across threads.
 *
 * @param proxyName unique proxy identifier in Toxiproxy's registry; used as the key for toxic
 *     management and proxy deletion; must be non-null and non-blank; restrict to {@code
 *     [a-zA-Z0-9_-]} to avoid shell and JSON issues
 * @param servicePort the real service's TCP port inside the container (e.g., 6379 for Redis, 5432
 *     for PostgreSQL); must be in [1, 65535]; this is the port clients connect to and what iptables
 *     redirects <em>from</em>
 * @param proxyPort the Toxiproxy listening port inside the container (convention: {@code
 *     servicePort + 10000}); must be in [1, 65535]; this is the port iptables redirects
 *     <em>to</em>, and where Toxiproxy listens; must differ from servicePort
 * @param containerHostname the address the test JVM uses to reach the container; obtained via
 *     {@code container.getHost()} (never hardcode "localhost"); used in the Toxiproxy API's {@code
 *     "listen"} field and returned to callers as the connection address
 * @author Christian Schnapka - Macstab GmbH
 */
public record ProxyConfiguration(
    @NonNull String proxyName, int servicePort, int proxyPort, @NonNull String containerHostname) {

  /**
   * Compact constructor — validates all invariants before field assignment.
   *
   * <p>The compact constructor form (no parameter list) intercepts the canonical constructor
   * generated by the record specification. All parameter assignments happen implicitly after this
   * block executes (Java Language Specification §8.10.4). Validation runs first, so an invalid
   * record instance is never observable.
   *
   * @throws NullPointerException if proxyName or containerHostname is null
   * @throws IllegalArgumentException if servicePort or proxyPort is outside [1, 65535]
   */
  public ProxyConfiguration {
    Objects.requireNonNull(proxyName, "proxyName must not be null");
    Objects.requireNonNull(containerHostname, "containerHostname must not be null");
    servicePort = validatePort(servicePort, "servicePort");
    proxyPort = validatePort(proxyPort, "proxyPort");
  }

  private static int validatePort(final int port, final String name) {
    if (port < 1 || port > 65535) {
      throw new IllegalArgumentException(
          String.format("%s must be in range [1, 65535], got: %d", name, port));
    }
    return port;
  }
}
